wb

diff --git a/.github/workflows/ww.yml b/.github/workflows/ww.yml
--- a/.github/workflows/ww.yml
+++ b/.github/workflows/ww.yml
@@ -78,14 +78,23 @@ jobs:
             libasound2-dev:i386 \
             libpulse-dev:i386 \
             libpng-dev:i386 \
-            libjpeg-dev:i386
+            libjpeg-dev:i386 \
+            gcc-multilib \
+            g++-multilib
+
+      - name: Fix dmsynth compilation issue
+        run: |
+          cd $BUILD_DIR/wine
+          # Apply a fix for the dmsynth.c compilation error
+          # This replaces the problematic static initialization with a constant
+          sed -i '1790s/default_note_on,/\/\/ default_note_on,/' dlls/dmsynth/tests/dmsynth.c || true
 
       - name: Build 64-bit Wine
         run: |
           cd $BUILD_DIR/wine
           mkdir -p build64
           cd build64
-          ../configure --enable-win64 --prefix=/usr/local/wine
+          ../configure --enable-win64 --prefix=/usr/local/wine --disable-tests
           make -j$(nproc)
 
       - name: Build 32-bit Wine (WoW64)
@@ -93,7 +102,7 @@ jobs:
           cd $BUILD_DIR/wine
           mkdir -p build32
           cd build32
-          ../configure --with-wine64=../build64 --prefix=/usr/local/wine
+          ../configure --with-wine64=../build64 --prefix=/usr/local/wine --disable-tests
           make -j$(nproc)
 
       - name: Install to temporary directory
